### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-readable-addon-folders#1]
The link is broken.

![image](https://user-images.githubusercontent.com/42243532/52479158-cf03e480-2b8e-11e9-9825-cfec711b462b.png)

**Comment by Arthur-Milchior** [comment]
Corrected thanks

Le ven. 8 févr. 2019 à 13:47, Carlos Duarte <notifications@github.com> a
écrit :

**Comment by cjdduarte** [comment]
in github is also :-)

![image](https://user-images.githubusercontent.com/42243532/52487322-89521680-2ba4-11e9-981b-fe9bdb27d589.png)
